172.16.1.11
/mnt/vmhost2/raid5/NNBS/
/mnt/backup/NNBS/
NNBS.tar.zstd
11
172.16.1.11
/mnt/vmhost2/raid5/util2-unify\ rebuild/
/mnt/backup/util2-unify\ rebuild/
util2-unify\ rebuild.tar.zstd
21
172.16.1.10
/mnt/vmhost0/vmhost0-local/SmartQC/
/mnt/backup/SmartQC/
SmartQC.tar.zstd
52
172.16.1.28
/mnt/vmhost1/vmhost1-local/Router_Main/
/mnt/backup/Router_Main/
Router_Main.tar.zstd
53
root@172.16.1.28
/mnt/vmhost1/vmhost1-local/jerry/
/mnt/backup/jerry/
jerry.tar.zstd
70
172.16.1.28
/mnt/vmhost0/vmhost0-local/utility3/
/mnt/backup/utility3/
utility3.tar.zstd
129
172.16.1.28
/mnt/vmhost0/vmhost0-local/BOBBIJO-VIRTUAL/
/mnt/backup/BOBBIJO-VIRTUAL/
BOBBIJO-VIRTUAL.tar.zstd
72
172.16.1.28
/mnt/vmhost0/vmhost0-local/HVAC\ PC/
/mnt/backup/HVAC\ PC/
HVAC\ PC.tar.zstd
131
172.16.1.28
/mnt/vmhost0/vmhost0-local/Unscrambler/
/mnt/backup/Unscrambler/
Unscrambler.tar.zstd
104
172.16.1.28
/mnt/vmhost0/vmhost0-local/Nik/
/mnt/backup/Nik/
Nik.tar.zstd
111
